
target "LJSYourNextBus" do
	pod 'ObjectiveGumbo', '~> 0.1'
	pod 'Masonry', '~> 0.4'
end

target "LJSYourNextBusTests" do
	pod 'OCMock', '~> 3.1'
	pod 'OCHamcrest', '~> 3.0'
	pod 'AGAsyncTestHelper', '~> 1.0'
end

