
target "LJSTravelSouthYorkshire" do
	pod "LJSTravelSouthYorkshire", :path => "../LJSTravelSouthYorkshire.podspec"
end

target "LJSTravelSouthYorkshireTests" do
	pod "LJSTravelSouthYorkshire", :path => "../LJSTravelSouthYorkshire.podspec"
    pod 'OCMock', '~> 2.2.2'
end

